const mongoose=require("mongoose")

const taskSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
        trim:true
    },
    description:{
        type:String,
        default:"",
        trim:true
    },
    project:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Project",
        required:true
    },
    assignedTo:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        default:null
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    priority:{
        type:String,
        enum:["Low","Medium","High"],
        default:"Medium"
    },
    status:{
        type:String,
        enum:["Todo","In Progress","Done"],
        default:"Todo"
    },
    dueDate:{
        type:Date,
        default:null
    },
    estimatedHours:{
        type:Number,
        default:0,
        min:0
    },
    labels:[
        {
            type:String,
            trim:true
        }
    ],
    completedAt:{
        type:Date,
        default:null
    }
},{
    timestamps:true
})

module.exports=mongoose.model("Task",taskSchema)