const express=require("express")
const authRouter=require('./routes/authRoutes')
const app=express()
const organizationRoutes=require("./routes/organization.routes")
const projectRoutes=require("./routes/project.routes")
const taskRoutes=require("./routes/task.routes")
const commentRoutes=require("./routes/comment.routes")
const attachmentRoutes=require("./routes/attachment.routes")
app.use(express.json())
app.use("/api/auth",authRouter)
app.use("/api/organizations",organizationRoutes)
app.use("/api/projects",projectRoutes)
app.use("/api/tasks",taskRoutes)
app.use("/api/comments",commentRoutes)
app.use("/api/attachments",attachmentRoutes)
module.exports=app